stages:
  - build
  - deploy

build_game:
  stage: build
  # 1.44.0 doesn't work because of https://github.com/rust-lang/rust/issues/72758
  # 1.46 nightly 2020-06-09 works
  image: rust:1.43.1
  before_script:
    - rustup target add wasm32-unknown-unknown
  script:
    - cargo build
    - cargo test
    - sh -c "cd client-web && cargo build --release --target wasm32-unknown-unknown"
    - mkdir output
    - cp target/wasm32-unknown-unknown/release/client_web.wasm output/
    - cp client-web/index.html client-web/index.js output/
  artifacts:
    paths:
      - output
  cache:
    paths:
      - /root/.cargo/registry
      - target

pages:
  stage: deploy
  script:
    - mkdir public
    - cp output/* public/
  artifacts:
    paths:
      - public
  only:
    - master
