stages:
  - build
  - deploy

build_game:
  stage: build
  image: remram/rust-cargo-web
  script:
    - cargo build
    - cargo test
    - (cd client-piston && cargo web build --release)
    - mkdir output &&
      cp target/asmjs-unknown-emscripten/release/client.js output/ &&
      cp target/asmjs-unknown-emscripten/release/deps/client-*.data output/ &&
      sed 's/"target\/asmjs-unknown-emscripten\/release\/client.js"/"client.js?'$(git rev-parse HEAD)'"/' <index.html >output/index.html
  artifacts:
    paths:
      - output
  cache:
    paths:
      - /root/.cargo/registry
      - target
  tags:
    - docker

pages:
  stage: deploy
  script:
    - mkdir public
    - cp output/* public/
  artifacts:
    paths:
      - public
  only:
    - master
