[package]
name = "vigilant-steel"
version = "0.1.0"
authors = ["Remi Rampin <remirampin@gmail.com>"]
license = "BSD-3-Clause"
repository = "https://gitlab.com/remram44/vigilant-steel"
description = "Space game with Piston"
readme = "README.md"
keywords = ["game"]

[[bin]]
name = "client"
path = "src/client.rs"

[[bin]]
name = "server"
path = "src/server.rs"

[dependencies]
env_logger = "0.4"
log = "0.3"
rand = "0.3"
specs = "0.10"
vecmath = "0.3"

# Abstract graphics
conrod = { version = "0.56", features = ["piston"] }
piston = "0.35"
piston2d-graphics = "0.23"

# Concrete graphics
piston2d-opengl_graphics = "0.49"
pistoncore-sdl2_window = "0.46"
sdl2 = "0.30"

[target.'cfg(target_os = "emscripten")'.dependencies]
emscripten-sys = "0.3"

[features]
default = ["sdl2/use_mac_framework"]
use_sdl2_mac_framework = ["sdl2/use_mac_framework"]
