[workspace]
members = ["client-piston", "server", "color-logger"]

[package]
name = "game"
version = "0.1.0"
authors = ["Remi Rampin <remirampin@gmail.com>"]
license = "BSD-3-Clause"
repository = "https://gitlab.com/remram44/vigilant-steel"
description = "Space game with Piston"
readme = "README.md"
keywords = ["game"]

[dependencies]
byteorder = "1"
log = "0.3"
rand = "0.3"
specs = "0.10"
vecmath = "0.3"

[features]
debug_markers = []
network = []
