[package]
workspace = ".."
name = "color-logger"
version = "0.2.0"
authors = ["Remi Rampin <remirampin@gmail.com>"]
license = "Unlicense/MIT"
description = "Simple log output with colors"

[dependencies]
log = { version = "0.4", features = ["std"] }
termcolor = "1.0"
